EXCLUDE = --exclude=.test-ipc --exclude=.test-sendrecv --exclude=.scipts --exclude=Makefile

re-build:
	cd ./offset && make re-build
	cd ./test-ipc && make re-build
	cd ./test-sendrecv && make re-build
	cd ./c++ && make re-build

clean:
	cd ./offset && make clean
	cd ./test-ipc && make clean
	cd ./test-sendrecv && make clean
	cd ./c++ && make clean
