EXCLUDE = --exclude=.test-ipc --exclude=.test-sendrecv --exclude=.scipts --exclude=Makefile

re-build:
	cd ./print_host && make re-build
	cd ./print_table && make re-build

clean:
	cd ./print_host && make clean
	cd ./print_table && make clean
